apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-web-deployment
  labels:
    app: ecommerce-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-web
  template:
    metadata:
      labels:
        app: ecommerce-web
    spec:
      containers:
        - name: ecommerce-web
          image: allyyahmad/ecommerce-frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
